version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=todoapp;User Id=sa;Password=Password123@;TrustServerCertificate=True;
      - JwtSettings__SecretKey=buraya-guclu-ve-uzun-bir-gizli-anahtar-yazin
      - JwtSettings__Issuer=TodoApp
      - JwtSettings__Audience=TodoApp
      - JwtSettings__ExpirationInMinutes=60
      - JwtSettings__RefreshTokenExpirationInDays=7
    depends_on:
      - db
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123@
    ports:
      - "1446:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

volumes:
  sqlserver_data:
